---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-odf-s3-secret
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: odf-s3-secret
subjects:
- kind: ServiceAccount
  name: job-odf-s3-secret
  namespace: openshift-adp
