---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role 
metadata:
  name: odf-s3-secret
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
