---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    openshift.io/cluster-monitoring: "true"
    openshift.io/node-selector: ''
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
  name: openshift-local-storage
