---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: annotate-storageclass
  namespace: openshift-storage
rules:
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  verbs:
  - get
  - list
  - patch
  - update
